# Generated by Django 4.1.7 on 2023-04-24 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0007_alter_donorinfo_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBags',
            fields=[
                ('bag_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_no', models.CharField(max_length=100)),
                ('date_donated', models.DateTimeField()),
                ('bled_by', models.CharField(max_length=50)),
                ('info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.donorinfo')),
            ],
        ),
    ]
