# Generated by Django 4.1.7 on 2023-04-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbags',
            name='serial_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
