# Generated by Django 4.1.7 on 2023-04-30 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_donorinfo_occupation'),
        ('inventory', '0005_alter_bloodbags_bled_by_alter_bloodbags_date_donated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbags',
            name='bled_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bloodbags',
            name='info_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.donorinfo'),
        ),
        migrations.AlterField(
            model_name='bloodbags',
            name='serial_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
