# Generated by Django 4.1.7 on 2023-05-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_bloodinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodinventory',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
