# Generated by Django 4.1.7 on 2023-05-20 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_bloodinventory_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiredBLood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expired_date', models.DateField()),
                ('blood_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.bloodinventory')),
            ],
        ),
    ]
