# Generated by Django 4.1.7 on 2023-05-21 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_bloodinventory_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expiredblood',
            name='id',
        ),
        migrations.AlterField(
            model_name='expiredblood',
            name='blood_inventory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory.bloodinventory'),
        ),
    ]
