# Generated by Django 4.1.7 on 2023-05-21 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_expiredblood_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiredblood',
            name='bag_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.bloodbags'),
        ),
    ]
