# Generated by Django 4.1.7 on 2023-05-21 02:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_expiredblood_bag_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expiredblood',
            name='blood_inventory',
        ),
        migrations.RemoveField(
            model_name='expiredblood',
            name='expired_date',
        ),
        migrations.AddField(
            model_name='expiredblood',
            name='exp_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='expiredblood',
            name='bag_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory.bloodbags'),
        ),
    ]
