# Generated by Django 4.1.7 on 2023-05-21 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_bloodinventory_bag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodinventory',
            name='bag_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.bloodbags'),
        ),
    ]
