# Generated by Django 4.1.7 on 2023-05-21 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_alter_donorinfo_info_id'),
        ('inventory', '0023_alter_bloodinventory_bag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbags',
            name='info_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.donorinfo'),
        ),
    ]
