# Generated by Django 4.1.7 on 2023-03-21 14:08

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('prcuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prcuser',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
