# Generated by Django 4.1.7 on 2023-03-27 14:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('prcuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prcuser',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='prcuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
