# Generated by Django 4.1.7 on 2023-03-27 14:19

from django.db import migrations, models
import prcuser.models


class Migration(migrations.Migration):

    dependencies = [
        ('prcuser', '0002_remove_prcuser_user_id_alter_prcuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prcuser',
            name='id',
            field=models.UUIDField(default=prcuser.models.generate_id, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
