# Generated by Django 4.1.7 on 2023-03-27 14:23

from django.db import migrations, models
import prcuser.models


class Migration(migrations.Migration):

    dependencies = [
        ('prcuser', '0003_alter_prcuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prcuser',
            name='id',
            field=models.CharField(default=prcuser.models.generate_id, editable=False, max_length=7, primary_key=True, serialize=False, unique=True),
        ),
    ]
