# Generated by Django 4.1.7 on 2023-03-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prcuser', '0003_alter_prcuser_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prcuser',
            name='age',
        ),
        migrations.AddField(
            model_name='prcuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
