# Generated by Django 4.1.7 on 2023-04-05 19:45

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorInfo',
            fields=[
                ('id', models.CharField(default=account.models.generate_id, editable=False, max_length=7, primary_key=True, serialize=False, unique=True)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('blood_type', models.CharField(choices=[('A+', 'A positive'), ('A-', 'A negative'), ('B+', 'B positive'), ('B-', 'B negative'), ('AB+', 'AB positive'), ('AB-', 'AB negative'), ('O+', 'O positive'), ('O-', 'O negative')], max_length=3)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('occupation', models.CharField(max_length=50)),
                ('age_years', models.IntegerField(default=0, editable=False)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(default='+639', max_length=128, region=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_privacy_accepted_terms_accepted', models.BooleanField(default=False)),
                ('is_consent_accepted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
