# Generated by Django 4.1.7 on 2023-04-06 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donorinfo',
            old_name='id',
            new_name='info_id',
        ),
    ]
