# Generated by Django 4.1.7 on 2023-04-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_id_donorinfo_info_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donorinfo',
            old_name='age_years',
            new_name='age',
        ),
    ]
