# Generated by Django 4.1.7 on 2023-04-06 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_age_years_donorinfo_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donorinfo',
            old_name='created_at',
            new_name='completed_at',
        ),
    ]
