# Generated by Django 4.1.7 on 2023-04-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_created_at_donorinfo_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorinfo',
            name='blood_type',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='donorinfo',
            name='sex',
            field=models.CharField(max_length=10),
        ),
    ]
