# Generated by Django 4.1.7 on 2023-04-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_donorinfo_blood_type_alter_donorinfo_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorinfo',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A positive'), ('A-', 'A negative'), ('B+', 'B positive'), ('B-', 'B negative'), ('AB+', 'AB positive'), ('AB-', 'AB negative'), ('O+', 'O positive'), ('O-', 'O negative')], max_length=3),
        ),
        migrations.AlterField(
            model_name='donorinfo',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
    ]
