# Generated by Django 4.1.7 on 2023-04-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_donorinfo_blood_type_alter_donorinfo_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorinfo',
            name='occupation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
