# Generated by Django 4.1.7 on 2023-05-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_donorinfo_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorinfo',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
