# Generated by Django 4.1.7 on 2023-05-03 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0007_alter_donorinfo_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deferral',
            fields=[
                ('deferral_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=30)),
                ('other_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(max_length=20)),
                ('info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.donorinfo')),
            ],
        ),
    ]
